"""appended plan_id column to payments

Revision ID: 21868a116813
Revises: 4a5e86ac0f4e
Create Date: 2026-02-01 18:53:53.956644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21868a116813'
down_revision: Union[str, Sequence[str], None] = '4a5e86ac0f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('plan_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'payments', 'plans', ['plan_id'], ['id'])
    op.execute("""
        CREATE TYPE paymentstatus AS ENUM 
        ('pending', 'succeeded', 'canceled', 'failed')
      """)
    op.add_column('payments', sa.Column('status', sa.Enum('pending', 'succeeded', 'canceled', 'failed', name='paymentstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'plan_id')

    # ### end Alembic commands  ###
