"""appended ai_verification column to works table

Revision ID: 3839eb4537d4
Revises: b58c0e6c4d01
Create Date: 2025-11-26 16:19:54.389128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3839eb4537d4'
down_revision: Union[str, Sequence[str], None] = 'b58c0e6c4d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('ai_verificated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'ai_verificated')
    # ### end Alembic commands ###
