"""renamed column name and updated Payments

Revision ID: 4a5e86ac0f4e
Revises: 55ddf20685d4
Create Date: 2026-02-01 18:05:59.080289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a5e86ac0f4e'
down_revision: Union[str, Sequence[str], None] = '55ddf20685d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('payment_provider_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_payments_payment_provider_id'), 'payments', ['payment_provider_id'], unique=False)
    op.drop_constraint(op.f('payments_plan_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('payments', 'yookassa_payment_id')
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'plan_id')
    op.add_column('plans', sa.Column('amount', sa.Integer(), nullable=False))
    op.drop_column('plans', 'payment')
    op.alter_column('subscriptions', 'used_checks',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'used_checks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('plans', sa.Column('payment', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('plans', 'amount')
    op.add_column('payments', sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('yookassa_payment_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_plan_id_fkey'), 'payments', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_payments_payment_provider_id'), table_name='payments')
    op.alter_column('payments', 'amount',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'payment_provider_id')
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
