"""rename file_keys to files

Revision ID: 548f62c561c8
Revises: 6503f27de08b
Create Date: 2026-01-17 18:09:53.452152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '548f62c561c8'
down_revision: Union[str, Sequence[str], None] = '6503f27de08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('files', sa.ARRAY(sa.String()), nullable=False, default=[]))
    op.drop_column('answers', 'file_keys')
    op.add_column('comments', sa.Column('files', sa.ARRAY(sa.String()), nullable=False, default=[]))
    op.drop_column('comments', 'file_keys')
    op.alter_column('exercises', 'files',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'files',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.add_column('comments', sa.Column('file_keys', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('comments', 'files')
    op.add_column('answers', sa.Column('file_keys', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('answers', 'files')
    # ### end Alembic commands ###
