"""updated subscription model

Revision ID: 55ddf20685d4
Revises: 7a740fb863e3
Create Date: 2026-02-01 16:56:49.496937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ddf20685d4'
down_revision: Union[str, Sequence[str], None] = '7a740fb863e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'payments', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    op.add_column('subscriptions', sa.Column('used_checks', sa.Integer(), nullable=False))
    op.drop_column('subscriptions', 'email_hash')
    op.drop_column('subscriptions', 'used_verifications_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('used_verifications_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('email_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'used_checks')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'plan_id')
    # ### end Alembic commands ###
