"""fix bug, with works.conclusion column

Revision ID: 5a8a789ff9dd
Revises: 800ef4e94123
Create Date: 2026-01-19 16:42:32.389670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8a789ff9dd'
down_revision: Union[str, Sequence[str], None] = '800ef4e94123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('conclusion', sa.String(), nullable=True))
    op.drop_column('works', 'сonclusion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('сonclusion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('works', 'conclusion')
    # ### end Alembic commands ###
