"""updated subscription model

Revision ID: 7a740fb863e3
Revises: 8637efacd98f
Create Date: 2026-01-29 18:05:35.591601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a740fb863e3'
down_revision: Union[str, Sequence[str], None] = '8637efacd98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('refund_limits', sa.Integer(), nullable=False))
    op.alter_column('plans', 'expiration_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('subscriptions', sa.Column('email_hash', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('self_writing', sa.Boolean(), nullable=False))
    op.add_column('subscriptions', sa.Column('finish_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('subscriptions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'started_at')
    op.drop_column('subscriptions', 'finish_at')
    op.drop_column('subscriptions', 'self_writing')
    op.drop_column('subscriptions', 'email_hash')
    op.alter_column('plans', 'expiration_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('plans', 'refund_limits')
    # ### end Alembic commands ###
