"""appended expiration days column in plans

Revision ID: 8637efacd98f
Revises: 60de4db80bc3
Create Date: 2026-01-28 16:13:52.656366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8637efacd98f'
down_revision: Union[str, Sequence[str], None] = '60de4db80bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('expiration_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'expiration_days')
    # ### end Alembic commands ###
