"""updated comments table

Revision ID: 8f90c87e92da
Revises: f4fb611a5507
Create Date: 2025-11-17 13:03:24.914678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f90c87e92da'
down_revision: Union[str, Sequence[str], None] = 'f4fb611a5507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('human', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'human')
    # ### end Alembic commands ###
