"""delete Files model

Revision ID: 934b2af5a5cf
Revises: 85f192e81212
Create Date: 2026-01-10 15:10:31.359964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '934b2af5a5cf'
down_revision: Union[str, Sequence[str], None] = '85f192e81212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_answer_file_id_fkey'), 'comments', type_='foreignkey')
    op.add_column('answers', sa.Column('file_keys', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('comments', sa.Column('answer_file_key', sa.String(), nullable=False))
    op.add_column('comments', sa.Column('file_keys', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('exercises', sa.Column('file_keys', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('comments', 'answer_file_id')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('exercises_files')
    op.drop_table('answers_files')
    op.drop_table('comments_files')
    op.drop_table('tasks_files')
    op.drop_table('files')
    op.add_column('tasks', sa.Column('image_keys', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'image_keys')
    op.drop_column('exercises', 'file_keys')
    op.add_column('comments', sa.Column('answer_file_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('comments_answer_file_id_fkey'), 'comments', 'files', ['answer_file_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'file_keys')
    op.drop_column('comments', 'answer_file_key')
    op.drop_column('answers', 'file_keys')
    op.create_table('tasks_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('tasks_files_file_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('tasks_files_task_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('comments_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('comments_files_comment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('comments_files_file_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('answers_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('answers_files_answer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('answers_files_file_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('exercises_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('exercises_files_exercise_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('exercises_files_file_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_mime', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('files_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey'))
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    # ### end Alembic commands ###
