"""rename column answer_file_key to answerfile_id in Comments table

Revision ID: af232a364647
Revises: e3b02dc32a40
Create Date: 2026-01-25 20:19:53.277683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af232a364647'
down_revision: Union[str, Sequence[str], None] = 'e3b02dc32a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('answerfile_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'comments', 'answerfiles', ['answerfile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'answer_file_key')
    op.drop_column('works', 'ai_verificated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('ai_verificated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('answer_file_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'answerfile_id')
    # ### end Alembic commands ###
