"""updated comments table
appended anser_file_id
normalize database by adding Coordinates table

Revision ID: b58c0e6c4d01
Revises: 8f90c87e92da
Create Date: 2025-11-25 11:35:47.264373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58c0e6c4d01'
down_revision: Union[str, Sequence[str], None] = '8f90c87e92da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordinates_id'), 'coordinates', ['id'], unique=False)
    op.drop_table('subjects_comment_types')
    op.add_column('comment_types', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.create_foreign_key('comment_types_subject_id_fkey', 'comment_types', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.add_column('comments', sa.Column('answer_file_id', sa.UUID(), nullable=False))
    op.create_foreign_key('comments_answer_file_id_fkey', 'comments', 'files', ['answer_file_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_answer_file_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'answer_file_id')
    op.drop_constraint('comment_types_subject_id_fkey', 'comment_types', type_='foreignkey')
    op.drop_column('comment_types', 'subject_id')
    op.create_table('subjects_comment_types',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comment_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_type_id'], ['comment_types.id'], name=op.f('subjects_comment_types_comment_type_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('subjects_comment_types_subject_id_fkey'))
    )
    op.drop_index(op.f('ix_coordinates_id'), table_name='coordinates')
    op.drop_table('coordinates')
    # ### end Alembic commands ###
