"""appended files table

Revision ID: e3b02dc32a40
Revises: 727fe8a91ffd
Create Date: 2026-01-24 17:45:37.968305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b02dc32a40'
down_revision: Union[str, Sequence[str], None] = '727fe8a91ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answerfiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('ai_status', sa.Enum('draft', 'verification', 'verificated', 'banned', name='statusanswerfile'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answerfiles_id'), 'answerfiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answerfiles_id'), table_name='answerfiles')
    op.drop_table('answerfiles')
    # ### end Alembic commands ###
