"""make unique constraint name_subject_teacher_uc for tasks

Revision ID: f08b4e48b027
Revises: 3839eb4537d4
Create Date: 2025-12-25 18:19:32.614138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08b4e48b027'
down_revision: Union[str, Sequence[str], None] = '3839eb4537d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subjects', ['name'])
    op.create_unique_constraint('_name_subject_teacher_uc', 'tasks', ['name', 'subject_id', 'teacher_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_subject_teacher_uc', 'tasks', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    # ### end Alembic commands ###
